export const Config = {
  author: {
    name: "Thiwanka Munasinghe",
    title: ["Geospatial Engineer", "Cartographer", "Python Developer"],
    location: "Gampaha, Sri Lanka",
    email: "thiwanka.munasinghe@hotmail.com",
  },

  socialLinks: {
    linkedin: "https://www.linkedin.com/in/thiwankamunasinghe",
    github: "https://github.com/thiwaK",
  },

  seo: {
    ogImage: "https://thiwak.github.io/route-elevation-engine/og-image.png",
    url: "https://thiwak.github.io/route-elevation-engine",
    twitterHandle: "@thiwaK",
    keywords: [
      "thiwaK",
      "thiwak",
      "Thiwanka",
      "thiwanka",
      "Thiwanka Munasinghe",
      "thiwanka munasinghe",
      "Thiwanka Kaushal",
      "thiwanka kaushal",
      "TK Munasinghe",
      "tk munasinghe",
      "TKM",
      "Thiwanka Kaushal Munasinghe",
      "thiwanka kaushal munasinghe",
      "Munasinghe MWTK",
      "MWTK Munasinghe",
      "MW Thiwanka Kaushal Munasinghe",
      "GIS",
      "gis",
      "Geospatial",
      "geospatial",
      "Remote Sensing",
      "GIS and RS",
      "GIS & RS",
      "Geographic Information System",
      "Geographical Information System",
      "Geographic Information Science",
      "Geographical Information Science",
      "GIS Developer",
      "Web Map",
      "GIS Dev",
      "Geospatial Solution Engineer",
      "GIS Analyst",
      "Remote Sensing Expert",
      "RS Expert",
      "Geographer",
      "Cartographer",
      "Data Analyst",
      "Data Engineer",
      "route-elevation-engine",
      "route elevation engine",
      "route-elevation",
      "route-engine",
      "elevation-engine",
      "route elevation",
      "route engine",
      "elevation engine",
    ],
    authors: [
      {
        name: "Thiwanka Munasinghe",
        url: "https://github.com/thiwaK",
      },
    ],
  },
};
